return (
    <div className="fixed top-0 pointer-events-none" style={{ left: '-20000px', opacity: 1, zIndex: -9999 }}>
      {/* 终极物理隐藏法：放到两万像素外，但保持 opacity: 1 强迫浏览器渲染 */}
      
      {/* 海报主容器 */}
      <div ref={containerRef} className="flex flex-col gap-10">
        {chunkedGames.map((pageGames, pageIndex) => (
          <div key={`page-${pageIndex}`} className="poster-page w-[800px] flex flex-col min-h-[800px]" style={{ backgroundColor: '#E60012' }}>
            
            {/* Header */}
            <div className="w-full bg-white p-10 flex flex-col justify-center border-b-8 relative" style={{ borderColor: '#111827' }}>
              <div className="flex items-center justify-between w-full">
                
                {/* Header 左侧：Logo 组合 */}
                <div className="flex items-center gap-4">
                  <img src="/images/logo.png" alt="Logo" className="h-14 w-auto object-contain" onError={(e) => { e.currentTarget.style.display = 'none'; }} />
                  <div className="text-5xl font-black italic tracking-tighter font-sans select-none" style={{ color: '#111827' }}>
                    S<span style={{ color: '#E60012' }}>x</span>ítčh D<span style={{ color: '#111827' }}>é</span><span style={{ color: '#E60012' }}>x</span>
                  </div>
                </div>

                {/* Header 右侧：Slogan 与 Category */}
                <div className="flex flex-col items-end">
                  <p className="text-2xl font-black tracking-widest" style={{ color: '#374151' }}>
                    诗和远方，和 Switch 奇
                  </p>
                  {/* 营销修复 1：动态海报标题 */}
                  <p className="text-xl font-black mt-1 uppercase" style={{ color: '#eab308' }}>
                    {posterCategory}
                  </p>
                </div>
              </div>

              {/* RENT/BUY 角标 */}
              <div className="absolute bottom-[-18px] right-10 px-6 py-2 border-4 rounded-full font-black uppercase tracking-widest text-sm z-10" style={{ backgroundColor: '#111827', color: '#ffffff', borderColor: '#E60012' }}>
                {labelText} SELECTION
              </div>
            </div>

            {/* 游戏网格区域 (4x3) */}
            <div className="p-8 flex flex-wrap gap-4 justify-start flex-grow">
              {pageGames.map((game, index) => {
                const price = isRental ? ((game.price * 0.35) / 5).toFixed(2) : game.price;
                return (
                  <div key={game.id} className="w-[calc(25%-12px)] rounded-xl p-3 flex flex-col shadow-xl" style={{ backgroundColor: '#ffffff' }}>
                    
                    <div className="relative w-full aspect-[3/4] mb-3">
                      <img 
                        src={getSafeImageUrl(game.imageUrl)} 
                        alt={game.title}
                        className="w-full h-full object-cover rounded-lg border" 
                        style={{ borderColor: '#f3f4f6' }} 
                        crossOrigin="anonymous" 
                        onError={(e) => { e.currentTarget.src = '/images/logo.png'; }}
                      />
                      
                      {/* 营销修复 2：随时退换营销标签 */}
                      {isRental && (
                        <div className="absolute top-2 right-2 px-2.5 py-1 rounded-full text-[10px] font-black shadow-md border tracking-wider" style={{ backgroundColor: '#25D366', color: '#ffffff', borderColor: 'rgba(255,255,255,0.4)' }}>
                          随时退换
                        </div>
                      )}
                    </div>

                    <h3 className="text-sm font-bold truncate mb-1" style={{ color: '#111827' }}>{game.title}</h3>
                    
                    <div className="mt-auto">
                      {/* 营销修复 3：加入 From 前缀 */}
                      <p className="font-black text-xl flex items-baseline" style={{ color: '#E60012' }}>
                        {isRental && <span className="text-xs font-bold mr-1" style={{ color: '#E60012' }}>From</span>}
                        RM {price}<span className="text-xs font-normal ml-1" style={{ color: '#6b7280' }}>{unitText}</span>
                      </p>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Footer */}
            <div className="w-full pb-8 flex justify-between px-10 text-sm tracking-[0.2em] font-bold uppercase" style={{ color: 'rgba(255,255,255,0.9)' }}>
              <span>Generated by Switch Dex Studio</span>
              <span>{pageIndex + 1} / {chunkedGames.length} {hasMore && '+'}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
