import React, { useEffect, useRef } from 'react';
import { toPng } from 'html-to-image';

export interface PosterGeneratorProps {
  games: any[];
  type: 'rental' | 'shop';
  triggerId: number | null; // 留着这个接口，但我们内部不做条件拦截了
  onGenerated: (imgUrl: string) => void;
  onError?: (err: any) => void;
}

export default function PosterGenerator({ games, type, triggerId, onGenerated, onError }: PosterGeneratorProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (triggerId === null || !containerRef.current) return;

    let isCancelled = false;

    const capture = async () => {
      try {
        await new Promise(resolve => requestAnimationFrame(resolve));
        await new Promise(resolve => setTimeout(resolve, 50)); 

        if (isCancelled || !containerRef.current) return;

        const images = Array.from(containerRef.current.querySelectorAll('img'));
        await Promise.all(
          images.map((img) => {
            if (img.complete || !img.src) return Promise.resolve();
            return new Promise((resolve) => {
              const timeout = setTimeout(resolve, 3000); 
              img.onload = () => { clearTimeout(timeout); resolve(null); };
              // 防爆机制：图片加载失败就换成logo
              img.onerror = () => { 
                clearTimeout(timeout); 
                img.src = '/images/logo.png'; 
                resolve(null); 
              }; 
            });
          })
        );

        if (isCancelled || !containerRef.current) return;

        // 原汁原味的截图
        const imgData = await toPng(containerRef.current, {
          pixelRatio: 2,
          // 强制红色底，不再是白屏
          backgroundColor: '#E60012', 
          style: { transform: 'none' },
        });

        if (!isCancelled) onGenerated(imgData);

      } catch (err) {
        console.error('Failed to generate poster:', err);
        if (!isCancelled && onError) onError(err);
      }
    };

    capture();

    return () => { isCancelled = true; };
  }, [triggerId, games, type, onGenerated, onError]);

  if (triggerId === null) return null;

  const posterGames = games.slice(0, 12);
  const isRental = type === 'rental';
  const labelText = isRental ? 'RENT' : 'BUY';
  const unitText = isRental ? '/mo' : '';

  const getSafeImageUrl = (url: string | undefined) => {
    if (!url) return '';
    if (url.startsWith('http')) {
      return `https://wsrv.nl/?url=${encodeURIComponent(url)}&output=webp`;
    }
    return url;
  };

  return (
    <div className="fixed top-0 z-[-9999] pointer-events-none" style={{ left: '-10000px' }}>
      {/* 强行注入纯正的任天堂红背景 */}
      <div ref={containerRef} className="w-[800px] flex flex-col min-h-[800px] p-10" style={{ backgroundColor: '#E60012' }}>
        
        {/* Header - 红底上的白字和黑字 Logo */}
        <div className="flex justify-between items-end mb-10 pb-6" style={{ borderBottomWidth: 2, borderBottomStyle: 'solid', borderColor: 'rgba(255,255,255,0.3)' }}>
          <div className="text-4xl font-black italic tracking-tighter font-sans select-none" style={{ color: '#ffffff' }}>
            S<span style={{ color: '#000000' }}>x</span>ítčh D<span style={{ color: '#ffffff' }}>é</span><span style={{ color: '#000000' }}>x</span>
          </div>
          <div className="px-6 py-2 rounded-full font-bold uppercase tracking-widest text-sm" style={{ backgroundColor: '#ffffff', color: '#E60012' }}>
            {labelText} SELECTION
          </div>
        </div>

        {/* 稳如泰山的 Flexbox 排版 */}
        <div className="flex flex-wrap gap-6 justify-between flex-grow">
          {posterGames.slice(0, 9).map((game) => {
            const price = isRental ? Math.floor(game.price * 0.06) : game.price;
            return (
              <div key={game.id} className="w-[calc(33.333%-16px)] rounded-xl p-4 flex flex-col" style={{ backgroundColor: '#ffffff' }}>
                <img src={getSafeImageUrl(game.imageUrl)} className="w-full aspect-[3/4] object-cover rounded-lg mb-4" crossOrigin={game.imageUrl?.startsWith('http') ? "anonymous" : undefined} referrerPolicy="no-referrer" />
                <h3 className="text-lg font-bold truncate mb-2" style={{ color: '#111827' }}>{game.title}</h3>
                <div className="mt-auto">
                  <p className="font-black text-2xl" style={{ color: '#E60012' }}>RM {price}<span className="text-sm font-normal ml-1" style={{ color: '#6b7280' }}>{unitText}</span></p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="w-full mt-10 text-center text-xs tracking-[0.3em] font-bold uppercase" style={{ color: 'rgba(255,255,255,0.7)' }}>
          Generated by Switch Dex Studio
        </div>
      </div>
    </div>
  );
}
